// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260823194657_AddPlayerSessionsTable")]
    partial class AddPlayerSessionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.OtpVerification", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("codeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("expiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("email");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("Backend.Models.PlayerProfileObj", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<int>("money")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("email");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Backend.Models.PlayerSession", b =>
                {
                    b.Property<string>("token")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("expiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("token");

                    b.ToTable("PlayerSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
