// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.OtpVerification", b =>
                {
                    b.Property<string>("emailHash")
                        .HasColumnType("text");

                    b.Property<string>("codeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("expiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("emailHash");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("Backend.Models.PlayerProfileObj", b =>
                {
                    b.Property<string>("emailHash")
                        .HasColumnType("text");

                    b.Property<int>("dayCount")
                        .HasColumnType("integer");

                    b.Property<int>("iceStock")
                        .HasColumnType("integer");

                    b.Property<int>("lemonStock")
                        .HasColumnType("integer");

                    b.Property<float>("money")
                        .HasColumnType("real");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("recipeIce")
                        .HasColumnType("integer");

                    b.Property<int>("recipeLemons")
                        .HasColumnType("integer");

                    b.Property<int>("recipeSugar")
                        .HasColumnType("integer");

                    b.Property<float>("salePrice")
                        .HasColumnType("real");

                    b.Property<int>("sugarStock")
                        .HasColumnType("integer");

                    b.HasKey("emailHash");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Backend.Models.PlayerSession", b =>
                {
                    b.Property<string>("tokenHash")
                        .HasColumnType("text");

                    b.Property<string>("emailHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("expiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("tokenHash");

                    b.ToTable("PlayerSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
