@Backend_HostAddress = http://localhost:5212

# Test 1: Register a new profile row into Postgres
POST {{Backend_HostAddress}}/api/player/register
Content-Type: application/json
{
  "name": "Test"
}

###

# Test 2: Read that newly written row directly back from Postgres
GET {{Backend_HostAddress}}/api/player/profile?pid=1
Accept: application/json

###
